server:
  port: 80
  servlet:
    context-path: /spring-demo

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.242.6:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: aini1314
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 39.107.242.6
    port: 6379
    database: 0   #Redis数据库索引（默认为0）
    password: 123456
    pool:
      max-active: 8    #最连接池最大连接数（使用负值表示没有限制）
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8     # 连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
    timeout: 0        # 连接超时时间（毫秒）

logging:
  level:
    cn.qblank.springdemo.domain.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml


